//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.30 at 07:05:23 PM BOT 
//


package com.kyron.geoserver;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/*
 * Auto-generated with java xjc.exe. Need a xsd file.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "enabled",
    "inMemoryCached",
    "name",
    "mimeFormats",
    "gridSubsets",
    "metaWidthHeight",
    "expireCache",
    "expireClients",
    "parameterFilters",
    "gutter"
})
@XmlRootElement(name = "GeoServerLayer")
public class GeoServerLayer {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String enabled;
    @XmlElement(required = true)
    protected String inMemoryCached;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected GeoServerLayer.MimeFormats mimeFormats;
    @XmlElement(required = true)
    protected GeoServerLayer.GridSubsets gridSubsets;
    @XmlElement(required = true)
    protected GeoServerLayer.MetaWidthHeight metaWidthHeight;
    protected byte expireCache;
    protected byte expireClients;
    @XmlElement(required = true)
    protected GeoServerLayer.ParameterFilters parameterFilters;
    protected byte gutter;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the inMemoryCached property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInMemoryCached() {
        return inMemoryCached;
    }

    /**
     * Sets the value of the inMemoryCached property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInMemoryCached(String value) {
        this.inMemoryCached = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mimeFormats property.
     * 
     * @return
     *     possible object is
     *     {@link GeoServerLayer.MimeFormats }
     *     
     */
    public GeoServerLayer.MimeFormats getMimeFormats() {
        return mimeFormats;
    }

    /**
     * Sets the value of the mimeFormats property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoServerLayer.MimeFormats }
     *     
     */
    public void setMimeFormats(GeoServerLayer.MimeFormats value) {
        this.mimeFormats = value;
    }

    /**
     * Gets the value of the gridSubsets property.
     * 
     * @return
     *     possible object is
     *     {@link GeoServerLayer.GridSubsets }
     *     
     */
    public GeoServerLayer.GridSubsets getGridSubsets() {
        return gridSubsets;
    }

    /**
     * Sets the value of the gridSubsets property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoServerLayer.GridSubsets }
     *     
     */
    public void setGridSubsets(GeoServerLayer.GridSubsets value) {
        this.gridSubsets = value;
    }

    /**
     * Gets the value of the metaWidthHeight property.
     * 
     * @return
     *     possible object is
     *     {@link GeoServerLayer.MetaWidthHeight }
     *     
     */
    public GeoServerLayer.MetaWidthHeight getMetaWidthHeight() {
        return metaWidthHeight;
    }

    /**
     * Sets the value of the metaWidthHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoServerLayer.MetaWidthHeight }
     *     
     */
    public void setMetaWidthHeight(GeoServerLayer.MetaWidthHeight value) {
        this.metaWidthHeight = value;
    }

    /**
     * Gets the value of the expireCache property.
     * 
     */
    public byte getExpireCache() {
        return expireCache;
    }

    /**
     * Sets the value of the expireCache property.
     * 
     */
    public void setExpireCache(byte value) {
        this.expireCache = value;
    }

    /**
     * Gets the value of the expireClients property.
     * 
     */
    public byte getExpireClients() {
        return expireClients;
    }

    /**
     * Sets the value of the expireClients property.
     * 
     */
    public void setExpireClients(byte value) {
        this.expireClients = value;
    }

    /**
     * Gets the value of the parameterFilters property.
     * 
     * @return
     *     possible object is
     *     {@link GeoServerLayer.ParameterFilters }
     *     
     */
    public GeoServerLayer.ParameterFilters getParameterFilters() {
        return parameterFilters;
    }

    /**
     * Sets the value of the parameterFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoServerLayer.ParameterFilters }
     *     
     */
    public void setParameterFilters(GeoServerLayer.ParameterFilters value) {
        this.parameterFilters = value;
    }

    /**
     * Gets the value of the gutter property.
     * 
     */
    public byte getGutter() {
        return gutter;
    }

    /**
     * Sets the value of the gutter property.
     * 
     */
    public void setGutter(byte value) {
        this.gutter = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="gridSubset" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="gridSetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gridSubset"
    })
    public static class GridSubsets {

        protected List<GeoServerLayer.GridSubsets.GridSubset> gridSubset;

        /**
         * Gets the value of the gridSubset property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gridSubset property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGridSubset().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeoServerLayer.GridSubsets.GridSubset }
         * 
         * 
         */
        public List<GeoServerLayer.GridSubsets.GridSubset> getGridSubset() {
            if (gridSubset == null) {
                gridSubset = new ArrayList<GeoServerLayer.GridSubsets.GridSubset>();
            }
            return this.gridSubset;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="gridSetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "gridSetName"
        })
        public static class GridSubset {

            @XmlElement(required = true)
            protected String gridSetName;

            /**
             * Gets the value of the gridSetName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGridSetName() {
                return gridSetName;
            }

            /**
             * Sets the value of the gridSetName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGridSetName(String value) {
                this.gridSetName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="int" type="{http://www.w3.org/2001/XMLSchema}byte" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_int"
    })
    public static class MetaWidthHeight {

        @XmlElement(name = "int", type = Byte.class)
        protected List<Byte> _int;

        /**
         * Gets the value of the int property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the int property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Byte }
         * 
         * 
         */
        public List<Byte> getInt() {
            if (_int == null) {
                _int = new ArrayList<Byte>();
            }
            return this._int;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "string"
    })
    public static class MimeFormats {

        protected List<String> string;

        /**
         * Gets the value of the string property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the string property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getString().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getString() {
            if (string == null) {
                string = new ArrayList<String>();
            }
            return this.string;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="styleParameterFilter">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "styleParameterFilter"
    })
    public static class ParameterFilters {

        @XmlElement(required = true)
        protected GeoServerLayer.ParameterFilters.StyleParameterFilter styleParameterFilter;

        /**
         * Gets the value of the styleParameterFilter property.
         * 
         * @return
         *     possible object is
         *     {@link GeoServerLayer.ParameterFilters.StyleParameterFilter }
         *     
         */
        public GeoServerLayer.ParameterFilters.StyleParameterFilter getStyleParameterFilter() {
            return styleParameterFilter;
        }

        /**
         * Sets the value of the styleParameterFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeoServerLayer.ParameterFilters.StyleParameterFilter }
         *     
         */
        public void setStyleParameterFilter(GeoServerLayer.ParameterFilters.StyleParameterFilter value) {
            this.styleParameterFilter = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "defaultValue"
        })
        public static class StyleParameterFilter {

            @XmlElement(required = true)
            protected String key;
            @XmlElement(required = true)
            protected String defaultValue;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the defaultValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultValue() {
                return defaultValue;
            }

            /**
             * Sets the value of the defaultValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultValue(String value) {
                this.defaultValue = value;
            }

        }

    }

}
