import com.kyron.drools.model.Message;
rule "Hello World"
      dialect "mvel"
  when
      m : Message( status == Message.HELLO, message : message )
  then
      System.out.println( message ); 
      modify ( m ) { message = "Goodbye cruel world",
                     status = Message.GOODBYE };
end
rule "Goodbye World"
      dialect "java"
  when
      m : Message( status == Message.GOODBYE, message : message )
  then
      System.out.println( message ); 
end