//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.26 at 02:03:33 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "generated_sources/myweb/accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package generated_sources.myweb.accountservice;
