apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: anh-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anh-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: custom_counter
      targetValue: 100  # Set your target value based on your metric

